version: '3.7'
services:
  dapr-sender:
    build: .
    image: dapr-sender
    container_name: dapr-sender
    environment:
      AZURE_SERVICE_BUS_HOST: ${AZURE_SERVICE_BUS_HOST}
      AZURE_SERVICE_BUS_USERNAME: ${AZURE_SERVICE_BUS_USERNAME}
      AZURE_SERVICE_BUS_PASSWORD: ${AZURE_SERVICE_BUS_PASSWORD}
      AZURE_SERVICE_BUS_QUEUE: ${AZURE_SERVICE_BUS_QUEUE}
      AZURE_SERVICE_BUS_TOPIC: ${AZURE_SERVICE_BUS_TOPIC}
