apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-asb
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: envvar-secret-store
      key: asb-connection-string
