apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: envvar-secret-store
  namespace: default
spec:
  type: secretstores.local.env
  version: v1
  metadata:
    - name: asb-connection-string
      value: ${AZURE_SERVICE_BUS_CONNECTION_STRING}
